description: "Grove Developer Interface Configuration YAML: this file is used to configure the Grove Developer Interface."
type: object
additionalProperties: false
properties:
  llms:
    description: "LLM configuration."
    type: object
    additionalProperties: false
    properties:
      default_llm_provider:
        description: "The default LLM provider to use."
        type: string
        enum:
          - "openai"
          - "deepseek"
          - "anthropic"
      llm_providers:
        description: "LLM providers configuration."
        type: object
        additionalProperties: false
        properties:
          openai:
            type: object
            additionalProperties: false
            properties:
              api_key:
                description: "API key for OpenAI."
                type: string
              client_model:
                description: "Client model for OpenAI."
                type: string
                enum:
                  - "o1-mini"
                  - "o1"
                  - "o3-mini"
                  - "gpt-4o"
          deepseek:
            type: object
            additionalProperties: false
            properties:
              api_key:
                description: "API key for DeepSeek."
                type: string
              client_model:
                description: "Client model for DeepSeek."
                type: string
                enum:
                  - "deepseek-chat"
                  - "deepseek-coder"
                  - "deepseek-reasoner"
          anthropic:
            type: object
            additionalProperties: false
            properties:
              api_key:
                description: "API key for Anthropic."
                type: string
              client_model:
                description: "Client model for Anthropic."
                type: string
                enum:
                  - "claude-3-5-haiku-latest"
                  - "claude-3-5-sonnet-latest"
                  - "claude-3-opus-20240229"
