description: "Grove Developer Interface Configuration YAML: this file is used to configure the Grove Developer Interface."
type: object
additionalProperties: false
properties:
  git_config:
    description: "Git configuration. This is used to configure your Git client for creating and pushing commits."
    type: object
    additionalProperties: false
    properties:
      personal_access_token:
        description: "Personal access token for GitHub. It must have at reast `repo` write scope to create pull requests."
        type: string
        pattern: "^(ghp_|gho_|ghu_|ghs_|ghr_|github_pat_)[a-zA-Z0-9_]{36,}$"
  llm_config:
    description: "LLM configuration. This is used to configure your LLM providers."
    type: object
    additionalProperties: false
    properties:
      default_llm_provider:
        description: "The default LLM provider to use. This may be overriden per-request using the `-p|--provider` flag."
        type: string
        enum:
          - "openai"
          - "deepseek"
          - "anthropic"
      llm_providers:
        description: "LLM providers configuration. This is used to configure your LLM providers."
        type: object
        additionalProperties: false
        properties:
          openai:
            type: object
            additionalProperties: false
            properties:
              api_key:
                description: "API key for OpenAI."
                type: string
              client_model:
                description: "Client model for OpenAI. This may be overriden per-request using the `-m|--model` flag."
                type: string
                enum:
                  - "o1-mini"
                  - "o1"
                  - "o3-mini"
                  - "gpt-4o"
          deepseek:
            type: object
            additionalProperties: false
            properties:
              api_key:
                description: "API key for DeepSeek."
                type: string
              client_model:
                description: "Client model for DeepSeek. This may be overriden per-request using the `-m|--model` flag."
                type: string
                enum:
                  - "deepseek-chat"
                  - "deepseek-coder"
                  - "deepseek-reasoner"
          anthropic:
            type: object
            additionalProperties: false
            properties:
              api_key:
                description: "API key for Anthropic."
                type: string
              client_model:
                description: "Client model for Anthropic. This may be overriden per-request using the `-m|--model` flag."
                type: string
                enum:
                  - "claude-3-5-haiku-latest"
                  - "claude-3-5-sonnet-latest"
                  - "claude-3-opus-20240229"
