# yaml-language-server: $schema=../config.schema.yaml
llms:
  default_llm_provider: deepseek
  llm_providers:
    openai:
      api_key: "your-openai-api-key"
      client_model: "gpt-4o"
    deepseek:
      api_key: "your-deepseek-api-key"
      client_model: "deepseek-coder"
    anthropic:
      api_key: "your-anthropic-api-key"
      client_model: "claude-3-5-haiku-latest"

